name: CICD

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      git_sha_short: ${{ '${{ steps.commit.outputs.short }}' }}
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Docker Login
        uses: docker/login-action@v3
        with: 
          username: ${{ '${{ secrets.DOCKER_USER }}' }}
          password: ${{ '${{ secrets.DOCKER_TOKEN }}' }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: javamllama/${{ values.app_name }}:${{ '${{ steps.commit.outputs.short }}' }}
  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Update the values file
        shell: bash
        run: |
          pip install yq
          echo ${{ '${{ needs.ci.outputs.git_sha_short }}' }}
          yq -Yi '.image.tag = "${{ '${{ needs.ci.outputs.git_sha_short }}' }}"' charts/${{ values.app_name }}/values-${{values.app_env}}.yaml
          cat charts/${{ values.app_name }}/values-${{ values.app_env}}.yaml

      - name: Push values.yml change back to repo
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updating values.yxml with new commit id ${{ '${{ needs.ci.outputs.git_sha_short }}' }}'

      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
          --insecure \
          --grpc-web \
          --username ${{ '${{ secrets.ARGO_USER }}' }} \
          --password ${{ '${{ secrets.ARGO_PASSWORD }}' }}
          argocd app sync ${{ values.app_name }}

